Health-Insurance-Management/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Health_Insurance_Management.Models;
using Health_Insurance_Management.Models.Enum;

namespace Health_Insurance_Management.Controllers
{
    public class EmployeesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Employees
        public async Task<ActionResult> Index()
        {
            var employees = db.Employees.Include(e => e.GetPolicy);
            return View(await employees.ToListAsync());
        }

        // GET: Employees/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = await db.Employees.FindAsync(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // GET: Employees/Create
        public ActionResult Create()
        {
            ViewBag.PolicyId = new SelectList(db.Policies, "PolicyId", "PolicyName");
            return View();
        }

        // POST: Employees/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "EmployeeId,PolicyId,EmployeeName,Designation,JoinDate,Salary,EmployeeAddress,EmployeePhone,Status,CreatedDate,UpdatedDate")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                employee.Status = Status.Active;
                employee.CreatedDate = DateTime.Now;
                db.Employees.Add(employee);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.PolicyId = new SelectList(db.Policies, "PolicyId", "PolicyName", employee.PolicyId);
            return View(employee);
        }

        // GET: Employees/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = await db.Employees.FindAsync(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            ViewBag.PolicyId = new SelectList(db.Policies, "PolicyId", "PolicyName", employee.PolicyId);
            return View(employee);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "EmployeeId,PolicyId,EmployeeName,Designation,JoinDate,Salary,EmployeeAddress,EmployeePhone,Status,CreatedDate,UpdatedDate")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                employee.UpdatedDate = DateTime.Now;
                
                db.Entry(employee).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.PolicyId = new SelectList(db.Policies, "PolicyId", "PolicyName", employee.PolicyId);
            return View(employee);
        }

        // GET: Employees/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = await db.Employees.FindAsync(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Employee employee = await db.Employees.FindAsync(id);
            db.Employees.Remove(employee);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet, ActionName("ChangeStatus")]
        public async Task<ActionResult> ChangStatus(int id)
        {
            var employee = await db.Employees.FindAsync(id);

            employee.Status = employee.Status == Status.Active ? Status.Deactive : Status.Active;
            db.Entry(employee).State = EntityState.Modified;
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Health-Insurance-Management/Controllers/HospitalController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Health_Insurance_Management.Models;
using Health_Insurance_Management.Models.Enum;

namespace Health_Insurance_Management.Controllers
{
    public class HospitalController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Hospital
        public ActionResult Index()
        {
            return View(db.HospitalInfos.ToList());
        }

        // GET: Hospital/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HospitalInfo hospitalInfo = db.HospitalInfos.Find(id);
            if (hospitalInfo == null)
            {
                return HttpNotFound();
            }
            return View(hospitalInfo);
        }

        // GET: Hospital/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Hospital/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "HospitalId,HospitalName,HospitalPhone,HospitalAddress,HospitalURL,Status,CreatedDate,UpdatedDate")] HospitalInfo hospitalInfo)
        {
            if (ModelState.IsValid)
            {
                hospitalInfo.Status = Status.Active;
                hospitalInfo.CreatedDate = DateTime.Now;
                hospitalInfo.UpdatedDate = DateTime.Now;
                db.HospitalInfos.Add(hospitalInfo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(hospitalInfo);
        }

        // GET: Hospital/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HospitalInfo hospitalInfo = db.HospitalInfos.Find(id);
            if (hospitalInfo == null)
            {
                return HttpNotFound();
            }
            return View(hospitalInfo);
        }

        // POST: Hospital/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "HospitalId,HospitalName,HospitalPhone,HospitalAddress,HospitalURL,Status,CreatedDate,UpdatedDate")] HospitalInfo hospitalInfo)
        {
            if (ModelState.IsValid)
            {
                hospitalInfo.UpdatedDate = DateTime.Now;
                db.Entry(hospitalInfo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(hospitalInfo);
        }

        // GET: Hospital/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HospitalInfo hospitalInfo = db.HospitalInfos.Find(id);
            if (hospitalInfo == null)
            {
                return HttpNotFound();
            }
            return View(hospitalInfo);
        }

        // POST: Hospital/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            HospitalInfo hospitalInfo = db.HospitalInfos.Find(id);
            db.HospitalInfos.Remove(hospitalInfo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet, ActionName("ChangeStatus")]
        public ActionResult ChangStatus(int id)
        {
            var hospital = db.HospitalInfos.Find(id);

            hospital.Status = hospital.Status == Status.Active ? Status.Deactive : Status.Active;
            db.Entry(hospital).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Health-Insurance-Management/Controllers/PoliciesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Health_Insurance_Management.Models;
using Health_Insurance_Management.Models.Enum;

namespace Health_Insurance_Management.Controllers
{
    public class PoliciesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Policies
        public async Task<ActionResult> Index()
        {
            var policies = db.Policies.Include(p => p.Company);
            return View(await policies.ToListAsync());
        }

        // GET: Policies/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Policy policy = await db.Policies.FindAsync(id);
            if (policy == null)
            {
                return HttpNotFound();
            }
            return View(policy);
        }

        // GET: Policies/Create
        public ActionResult Create()
        {
            ViewBag.CompanyId = new SelectList(db.CompanyDetails, "CompanyId", "CompanyName");
            return View();
        }

        // POST: Policies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "PolicyId,CompanyId,PolicyName,PolicyDescription,Amount,Emi,MedicalId,Status,CreatedDate,UpdatedDate")] Policy policy)
        {
            if (ModelState.IsValid)
            {
                policy.Status = Status.Active;
                policy.CreatedDate = DateTime.Now;
                db.Policies.Add(policy);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.CompanyId = new SelectList(db.CompanyDetails, "CompanyId", "CompanyName", policy.CompanyId);
            return View(policy);
        }

        // GET: Policies/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Policy policy = await db.Policies.FindAsync(id);
            if (policy == null)
            {
                return HttpNotFound();
            }
            ViewBag.CompanyId = new SelectList(db.CompanyDetails, "CompanyId", "CompanyName", policy.CompanyId);
            return View(policy);
        }

        // POST: Policies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "PolicyId,CompanyId,PolicyName,PolicyDescription,Amount,Emi,MedicalId,Status,CreatedDate,UpdatedDate")] Policy policy)
        {
            if (ModelState.IsValid)
            {
                policy.UpdatedDate = DateTime.Now;
                db.Entry(policy).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.CompanyId = new SelectList(db.CompanyDetails, "CompanyId", "CompanyName", policy.CompanyId);
            return View(policy);
        }

        // GET: Policies/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Policy policy = await db.Policies.FindAsync(id);
            if (policy == null)
            {
                return HttpNotFound();
            }
            return View(policy);
        }

        // POST: Policies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            var employeePolicy = await db.PolicyOnEmployees.Where(x => x.PolicyId == id).ToArrayAsync();
            foreach(var item in employeePolicy)
            {
                db.PolicyOnEmployees.Remove(item);
                await db.SaveChangesAsync();
            }

            Policy policy = await db.Policies.FindAsync(id);

            db.Policies.Remove(policy);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet, ActionName("ChangeStatus")]
        public async Task<ActionResult> ChangStatus(int id)
        {
            var policy = await db.Policies.FindAsync(id);

            policy.Status = policy.Status == Status.Active ? Status.Deactive : Status.Active;
            db.Entry(policy).State = EntityState.Modified;
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Health-Insurance-Management/Views/Admin/Layout/_MainSidebar.cshtml
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="~/Content/Admin/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>@ViewBag.EmailLogin</p>
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>
        <!-- search form -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
                <span class="input-group-btn">
                    <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                        <i class="fa fa-search"></i>
                    </button>
                </span>
            </div>
        </form>
        <!-- /.search form -->
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">MAIN NAVIGATION</li>
            <li class="active treeview">
                <a href="#">
                    <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class="active"><a href="index.html"><i class="fa fa-circle-o"></i> Dashboard v1</a></li>
                    <li><a href="index2.html"><i class="fa fa-circle-o"></i> Dashboard v2</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-table"></i> <span>Admin</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="pages/tables/simple.html"><i class="fa fa-circle-o"></i> Simple tables</a></li>
                    <li><a href="pages/tables/data.html"><i class="fa fa-circle-o"></i> Data tables</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-table"></i> <span>Employee</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="@Url.Action("Index","Employees")"><i class="fa fa-circle-o"></i>View All</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-table"></i> <span>Policy</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="@Url.Action("Index","Policies")"><i class="fa fa-circle-o"></i>View All</a></li>
                    <li><a href="@Url.Action("Index","PolicyOnEmployees")"><i class="fa fa-circle-o"></i>Employee Policy</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-table"></i> <span>Company Details</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="@Url.Action("Index","CompanyDetails")"><i class="fa fa-circle-o"></i>View All</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-table"></i> <span>Hospital</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="@Url.Action("Index","Hospital")"><i class="fa fa-circle-o"></i>View All</a></li>
                </ul>
            </li>
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>