Health-Insurance-Management/Models/CompanyDetail.cs
using Health_Insurance_Management.Models.Enum;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Health_Insurance_Management.Models
{
    public class CompanyDetail
    {
        [Key]
        public int CompanyId { get; set; }
        [Required]
        public string CompanyName { get; set; }
        [Required]
        public string CompanyAddress { get; set; }
        [Required]
        public string CompanyPhone { get; set; }
        public string CompanyURL { get; set; }
        public Status Status { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
    }
}

Health-Insurance-Management/Controllers/CompanyDetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Health_Insurance_Management.Models;
using Health_Insurance_Management.Models.Enum;

namespace Health_Insurance_Management.Controllers
{
    public class CompanyDetailsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: CompanyDetails
        public ActionResult Index()
        {
            return View(db.CompanyDetails.ToList());
        }

        // GET: CompanyDetails/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompanyDetail companyDetail = db.CompanyDetails.Find(id);
            if (companyDetail == null)
            {
                return HttpNotFound();
            }
            return View(companyDetail);
        }

        // GET: CompanyDetails/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CompanyDetails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CompanyId,CompanyName,CompanyAddress,CompanyPhone,CompanyURL,Status,CreatedDate,UpdatedDate")] CompanyDetail companyDetail)
        {
            if (ModelState.IsValid)
            {
                companyDetail.Status = Status.Active;
                companyDetail.CreatedDate = DateTime.Now;
                companyDetail.UpdatedDate = DateTime.Now;
                db.CompanyDetails.Add(companyDetail);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(companyDetail);
        }

        // GET: CompanyDetails/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompanyDetail companyDetail = db.CompanyDetails.Find(id);
            if (companyDetail == null)
            {
                return HttpNotFound();
            }
            return View(companyDetail);
        }

        // POST: CompanyDetails/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CompanyId,CompanyName,CompanyAddress,CompanyPhone,CompanyURL,Status,CreatedDate,UpdatedDate")] CompanyDetail companyDetail)
        {
            if (ModelState.IsValid)
            {
                companyDetail.UpdatedDate = DateTime.Now;
                db.Entry(companyDetail).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(companyDetail);
        }

        // GET: CompanyDetails/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompanyDetail companyDetail = db.CompanyDetails.Find(id);
            if (companyDetail == null)
            {
                return HttpNotFound();
            }
            return View(companyDetail);
        }

        // POST: CompanyDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CompanyDetail companyDetail = db.CompanyDetails.Find(id);
            db.CompanyDetails.Remove(companyDetail);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet, ActionName("ChangeStatus")]
        public async Task<ActionResult> ChangStatus(int id)
        {
            var company = await db.CompanyDetails.FindAsync(id);

            company.Status = company.Status == Status.Active ? Status.Deactive : Status.Active;
            db.Entry(company).State = EntityState.Modified;
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Health-Insurance-Management/Views/CompanyDetails/Create.cshtml
@model Health_Insurance_Management.Models.CompanyDetail

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Admin/Layout/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <section class="content-header">
        <h1>
            Health-Insurance-Management
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i>Home</a></li>
            <li><a href="#">Company Details</a></li>
            <li class="active">Create New</li>
        </ol>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Create Company</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    <form role="form" action="@Url.Action("Create")" method="post">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="box-body">
                            <div class="form-group">
                                @Html.LabelFor(model => model.CompanyName, htmlAttributes: new { @class = "control-label" })
                                <div class="">
                                    @Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.CompanyAddress, htmlAttributes: new { @class = "control-label" })
                                <div class="">
                                    @Html.EditorFor(model => model.CompanyAddress, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.CompanyAddress, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.CompanyPhone, htmlAttributes: new { @class = "control-label" })
                                <div class="">
                                    @Html.EditorFor(model => model.CompanyPhone, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.CompanyPhone, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.CompanyURL, htmlAttributes: new { @class = "control-label" })
                                <div class="">
                                    @Html.EditorFor(model => model.CompanyURL, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.CompanyURL, "", new { @class = "text-danger" })
                                </div>
                            </div>

                        </div>
                        <!-- /.box-body -->

                        <div class="box-footer">
                            <input type="submit" value="Create" class="btn btn-success" />
                        </div>
                    </form>
                </div>
                <a href="@Url.Action("Index", "CompanyDetails")" class="btn btn-info"> <= Back to List</a>
                <!-- /.box -->
            </div>
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->

}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Health-Insurance-Management/Views/CompanyDetails/Delete.cshtml
@model Health_Insurance_Management.Models.CompanyDetail

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Admin/Layout/_Layout.cshtml";
}

<div class="content">
    <h4>Company: @Html.DisplayNameFor(model => model.CompanyName)</h4>
    <hr />
    <div class="row">
        <div class="col-md-12">
            <p class="lead">Are you sure you want to delete this?</p>

            <div class="table-responsive">
                <table class="table">
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.CompanyName):</th>
                        <td>@Html.DisplayFor(model => model.CompanyName)</td>
                    </tr>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.CompanyAddress):</th>
                        <td>@Html.DisplayFor(model => model.CompanyAddress)</td>
                    </tr>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.CompanyPhone):</th>
                        <td>@Html.DisplayFor(model => model.CompanyPhone)</td>
                    </tr>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.CompanyURL):</th>
                        <td>@Html.DisplayFor(model => model.CompanyURL)</td>
                    </tr>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.Status):</th>
                        <td>@Html.DisplayFor(model => model.Status)</td>
                    </tr>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.CreatedDate):</th>
                        <td>@Html.DisplayFor(model => model.CreatedDate)</td>
                    </tr>
                </table>
            </div>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-danger" onclick="return confirm('All information of company will be deleted !')" /> |
                    @Html.ActionLink("Back to List", "Index")
                </div>
            }
        </div>
    </div>
</div>

Health-Insurance-Management/Views/CompanyDetails/Details.cshtml
@model Health_Insurance_Management.Models.CompanyDetail

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Admin/Layout/_Layout.cshtml";
}

<div class="content">
    <h4>Company Detail: @Html.DisplayNameFor(model => model.CompanyName)</h4>
    <hr />
    <div class="row">
        <div class="col-md-12">
            <div class="table-responsive">
                <table class="table">
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.CompanyName):</th>
                        <td>@Html.DisplayFor(model => model.CompanyName)</td>
                    </tr>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.CompanyAddress):</th>
                        <td>@Html.DisplayFor(model => model.CompanyAddress)</td>
                    </tr>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.CompanyPhone):</th>
                        <td>@Html.DisplayFor(model => model.CompanyPhone)</td>
                    </tr>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.CompanyURL):</th>
                        <td>@Html.DisplayFor(model => model.CompanyURL)</td>
                    </tr>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.Status):</th>
                        <td>@Html.DisplayFor(model => model.Status)</td>
                    </tr>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.CreatedDate):</th>
                        <td>@Html.DisplayFor(model => model.CreatedDate)</td>
                    </tr>
                </table>
            </div>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="form-actions no-color">
                    <a href="@Url.Action("Edit", "CompanyDetails", new { id = Model.CompanyId })" class="btn btn-info">Edit</a> |
                    @Html.ActionLink("Back to List", "Index")
                </div>
            }
        </div>
    </div>
</div>

Health-Insurance-Management/Views/CompanyDetails/Edit.cshtml
@model Health_Insurance_Management.Models.CompanyDetail

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Admin/Layout/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <section class="content-header">
        <h1>
            Health-Insurance-Management
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Company Details</a></li>
            <li class="active">Edit</li>
        </ol>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Edit Company</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    <form role="form" action="@Url.Action("Edit")" method="post">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.CompanyId)
                        <div class="box-body">
                            <div class="form-group">
                                @Html.LabelFor(model => model.CompanyName, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.CompanyAddress, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.CompanyAddress, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.CompanyAddress, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.CompanyPhone, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.CompanyPhone, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.CompanyPhone, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.CompanyURL, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.CompanyURL, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.CompanyURL, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control", @type = "hidden" } })

                        </div>
                        <!-- /.box-body -->

                        <div class="box-footer">
                            <input type="submit" value="Save" class="btn btn-success" />
                        </div>
                    </form>
                </div>
                <a href="@Url.Action("Index", "CompanyDetails")" class="btn btn-info"> <= Back to List</a>
                <!-- /.box -->
            </div>
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Health-Insurance-Management/Views/CompanyDetails/Index.cshtml
@model IEnumerable<Health_Insurance_Management.Models.CompanyDetail>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Admin/Layout/_Layout.cshtml";
}

<section class="content-header">
    <h1>
        Health-Insurance-Management
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Company Details</a></li>
        <li class="active">View All</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <button class="btn btn-success" style="color: white;">
        @Html.ActionLink("Create New", "Create")
    </button>
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">CompanyDetails</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="example1" class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Name</th>
                                <th>Address</th>
                                <th>Phone</th>
                                <th>Company URL</th>
                                <th>Status</th>
                                <th>Created At</th>
                                <th>Updated At</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.CompanyId)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.CompanyName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.CompanyAddress)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.CompanyPhone)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.CompanyURL)
                                    </td>
                                    <td>
                                        @if (item.Status == Health_Insurance_Management.Models.Enum.Status.Active)
                                        {
                                            <span class="label label-success">@Html.DisplayFor(modelItem => item.Status)</span>
                                        }
                                        else
                                        {
                                            <span class="label label-warning">@Html.DisplayFor(modelItem => item.Status)</span>
                                        }

                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.CreatedDate)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.UpdatedDate)
                                    </td>
                                    <td>
                                        <div class="btn-group">
                                            <button type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown">Action</button>
                                            <ul class="dropdown-menu" role="menu">
                                                @if (item.Status == Health_Insurance_Management.Models.Enum.Status.Active)
                                                {
                                                    <li><a href="@Url.Action("ChangeStatus", "CompanyDetails", new { id = item.CompanyId })">DeActive</a></li>
                                                }
                                                else
                                                {
                                                    <li><a href="@Url.Action("ChangeStatus", "CompanyDetails", new { id = item.CompanyId })">Active</a></li>
                                                }
                                                <li class="divider"></li>
                                                <li><a href="@Url.Action("Details", "CompanyDetails", new { id = item.CompanyId })">View Detail</a></li>
                                                <li><a href="@Url.Action("Edit", "CompanyDetails", new { id = item.CompanyId })">Edit</a></li>
                                                <li><a href="@Url.Action("Delete", "CompanyDetails", new { id = item.CompanyId })">Delete</a></li>
                                            </ul>
                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>