Health-Insurance-Management/Models/PolicyOnEmployee.cs
using Health_Insurance_Management.Models.Enum;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Health_Insurance_Management.Models
{
    public class PolicyOnEmployee
    {
        [Key]
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        [ForeignKey("EmployeeId")]
        public virtual Employee Employee { get; set; }
        public int PolicyId { get; set; }
        [ForeignKey("PolicyId")]
        public virtual Policy Policy { get; set; }
        [Required]
        public DateTime StartDate { get; set; }
        [Required]
        public DateTime EndDate { get; set; }
        public Status Status { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
    }
}

Health-Insurance-Management/Controllers/PolicyOnEmployeesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Health_Insurance_Management.Models;
using Health_Insurance_Management.Models.Enum;

namespace Health_Insurance_Management.Controllers
{
    public class PolicyOnEmployeesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: PolicyOnEmployees
        public async Task<ActionResult> Index()
        {
            var policyOnEmployees = db.PolicyOnEmployees.Include(p => p.Employee).Include(p => p.Policy);
            return View(await policyOnEmployees.ToListAsync());
        }

        // GET: PolicyOnEmployees/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PolicyOnEmployee policyOnEmployee = await db.PolicyOnEmployees.FindAsync(id);
            if (policyOnEmployee == null)
            {
                return HttpNotFound();
            }
            return View(policyOnEmployee);
        }

        // GET: PolicyOnEmployees/Create
        public ActionResult Create()
        {
            ViewBag.EmployeeId = new SelectList(db.Employees, "EmployeeId", "EmployeeName");
            ViewBag.PolicyId = new SelectList(db.Policies, "PolicyId", "PolicyName");
            return View();
        }

        // POST: PolicyOnEmployees/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,EmployeeId,PolicyId,StartDate,EndDate,Status,CreatedDate,UpdatedDate")] PolicyOnEmployee policyOnEmployee)
        {
            if (ModelState.IsValid)
            {
                policyOnEmployee.CreatedDate = DateTime.Now;
                db.PolicyOnEmployees.Add(policyOnEmployee);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.EmployeeId = new SelectList(db.Employees, "EmployeeId", "EmployeeName", policyOnEmployee.EmployeeId);
            ViewBag.PolicyId = new SelectList(db.Policies, "PolicyId", "PolicyName", policyOnEmployee.PolicyId);
            return View(policyOnEmployee);
        }

        // GET: PolicyOnEmployees/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PolicyOnEmployee policyOnEmployee = await db.PolicyOnEmployees.FindAsync(id);
            if (policyOnEmployee == null)
            {
                return HttpNotFound();
            }
            ViewBag.EmployeeId = new SelectList(db.Employees, "EmployeeId", "EmployeeName", policyOnEmployee.EmployeeId);
            ViewBag.PolicyId = new SelectList(db.Policies, "PolicyId", "PolicyName", policyOnEmployee.PolicyId);
            return View(policyOnEmployee);
        }

        // POST: PolicyOnEmployees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,EmployeeId,PolicyId,StartDate,EndDate,Status,CreatedDate,UpdatedDate")] PolicyOnEmployee policyOnEmployee)
        {
            if (ModelState.IsValid)
            {
                policyOnEmployee.UpdatedDate = DateTime.Now;
                db.Entry(policyOnEmployee).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.EmployeeId = new SelectList(db.Employees, "EmployeeId", "EmployeeName", policyOnEmployee.EmployeeId);
            ViewBag.PolicyId = new SelectList(db.Policies, "PolicyId", "PolicyName", policyOnEmployee.PolicyId);
            return View(policyOnEmployee);
        }

        // GET: PolicyOnEmployees/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PolicyOnEmployee policyOnEmployee = await db.PolicyOnEmployees.FindAsync(id);
            if (policyOnEmployee == null)
            {
                return HttpNotFound();
            }
            return View(policyOnEmployee);
        }

        // POST: PolicyOnEmployees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            PolicyOnEmployee policyOnEmployee = await db.PolicyOnEmployees.FindAsync(id);
            db.PolicyOnEmployees.Remove(policyOnEmployee);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet, ActionName("ChangeStatus")]
        public async Task<ActionResult> ChangStatus(int id)
        {
            var policyOnEmployee = await db.PolicyOnEmployees.FindAsync(id);

            policyOnEmployee.Status = policyOnEmployee.Status == Status.Active ? Status.Deactive : Status.Active;
            db.Entry(policyOnEmployee).State = EntityState.Modified;
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Health-Insurance-Management/Views/PolicyOnEmployees/Create.cshtml
@model Health_Insurance_Management.Models.PolicyOnEmployee

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Admin/Layout/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <section class="content-header">
        <h1>
            Health-Insurance-Management
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Employee Policy</a></li>
            <li class="active">Create</li>
        </ol>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Create Employee</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    <form role="form" action="@Url.Action("Create")" method="post">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="box-body">
                            <div class="form-group">
                                <label>Employee</label>
                                @Html.DropDownList("EmployeeId", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.EmployeeId, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <label>Policy</label>
                                @Html.DropDownList("PolicyId", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.PolicyId, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <label>Join Date</label>
                                <div class="input-group date">
                                    <div class="input-group-addon">
                                        <i class="fa fa-calendar"></i>
                                    </div>
                                    @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control pull-right", @id = "datepicker" } })
                                </div>
                                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <label>Join Date</label>
                                <div class="input-group date">
                                    <div class="input-group-addon">
                                        <i class="fa fa-calendar"></i>
                                    </div>
                                    @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control pull-right", @id = "datepicker-1" } })
                                </div>
                                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <!-- /.box-body -->

                        <div class="box-footer">
                            <input type="submit" value="Create" class="btn btn-success" />
                        </div>
                    </form>
                </div>
                <a href="@Url.Action("Index", "PolicyOnEmployees")" class="btn btn-info"> <= Back to List</a>
                <!-- /.box -->
            </div>
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Health-Insurance-Management/Views/PolicyOnEmployees/Delete.cshtml
@model Health_Insurance_Management.Models.PolicyOnEmployee

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Admin/Layout/_Layout.cshtml";
}

<div class="content">
    <h4>Employee Policy: @Html.DisplayNameFor(model => model.Employee.EmployeeName)</h4>
    <hr />
    <div class="row">
        <div class="col-md-12">
            <p class="lead">Are you sure you want to delete this?</p>

            <div class="table-responsive">
                <table class="table">
                    <tr>
                        <th> @Html.DisplayNameFor(model => model.Employee.EmployeeName):</th>
                        <td> @Html.DisplayNameFor(model => model.Employee.EmployeeName)</td>
                    </tr>
                    <tr>
                        <th> @Html.DisplayNameFor(model => model.Policy.PolicyName):</th>
                        <td> @Html.DisplayNameFor(model => model.Policy.PolicyName)</td>
                    </tr>
                    <tr>
                        <th> @Html.DisplayNameFor(model => model.StartDate):</th>
                        <td> @Html.DisplayNameFor(model => model.StartDate)</td>
                    </tr>
                    <tr>
                        <th> @Html.DisplayNameFor(model => model.EndDate):</th>
                        <td> @Html.DisplayNameFor(model => model.EndDate)</td>
                    </tr>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.Status):</th>
                        <td>@Html.DisplayFor(model => model.Status)</td>
                    </tr>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.CreatedDate):</th>
                        <td>@Html.DisplayFor(model => model.CreatedDate)</td>
                    </tr>
                </table>
            </div>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-danger" /> |
                    @Html.ActionLink("Back to List", "Index")
                </div>
            }
        </div>
    </div>
</div>

Health-Insurance-Management/Views/PolicyOnEmployees/Details.cshtml
@model Health_Insurance_Management.Models.PolicyOnEmployee

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Admin/Layout/_Layout.cshtml";
}

<div class="content">
    <h4>Employee Policy: @Html.DisplayNameFor(model => model.Employee.EmployeeName)</h4>
    <hr />
    <div class="row">
        <div class="col-md-12">
            <div class="table-responsive">
                <table class="table">
                    <tr>
                        <th> @Html.DisplayNameFor(model => model.Employee.EmployeeName):</th>
                        <td> @Html.DisplayNameFor(model => model.Employee.EmployeeName)</td>
                    </tr>
                    <tr>
                        <th> @Html.DisplayNameFor(model => model.Policy.PolicyName):</th>
                        <td> @Html.DisplayNameFor(model => model.Policy.PolicyName)</td>
                    </tr>
                    <tr>
                        <th> @Html.DisplayNameFor(model => model.StartDate):</th>
                        <td> @Html.DisplayNameFor(model => model.StartDate)</td>
                    </tr>
                    <tr>
                        <th> @Html.DisplayNameFor(model => model.EndDate):</th>
                        <td> @Html.DisplayNameFor(model => model.EndDate)</td>
                    </tr>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.Status):</th>
                        <td>@Html.DisplayFor(model => model.Status)</td>
                    </tr>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.CreatedDate):</th>
                        <td>@Html.DisplayFor(model => model.CreatedDate)</td>
                    </tr>
                </table>
            </div>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="form-actions no-color">
                    <a href="@Url.Action("Edit", "PolicyOnEmployees", new { id = Model.EmployeeId })" class="btn btn-info">Edit</a> |
                    @Html.ActionLink("Back to List", "Index")
                </div>
            }
        </div>
    </div>
</div>

Health-Insurance-Management/Views/PolicyOnEmployees/Edit.cshtml
@model Health_Insurance_Management.Models.PolicyOnEmployee

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Admin/Layout/_Layout.cshtml";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <section class="content-header">
        <h1>
            Health-Insurance-Management
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Employee Policy</a></li>
            <li class="active">Create</li>
        </ol>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Create Employee</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    <form role="form" action="@Url.Action("Edit")" method="post">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="box-body">
                            <div class="form-group">
                                <label>Employee</label>
                                @Html.DropDownList("EmployeeId", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.EmployeeId, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <label>Policy</label>
                                @Html.DropDownList("PolicyId", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.PolicyId, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <label>Join Date</label>
                                <div class="input-group date">
                                    <div class="input-group-addon">
                                        <i class="fa fa-calendar"></i>
                                    </div>
                                    @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control pull-right", @id = "datepicker" } })
                                </div>
                                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <label>Join Date</label>
                                <div class="input-group date">
                                    <div class="input-group-addon">
                                        <i class="fa fa-calendar"></i>
                                    </div>
                                    @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control pull-right", @id = "datepicker" } })
                                </div>
                                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
                            </div>
                            @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control", @type = "hidden" } })
                        </div>
                        <!-- /.box-body -->

                        <div class="box-footer">
                            <input type="submit" value="Save" class="btn btn-success" />
                        </div>
                    </form>
                </div>
                <a href="@Url.Action("Index", "PolicyOnEmployees")" class="btn btn-info"> <= Back to List</a>
                <!-- /.box -->
            </div>
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Health-Insurance-Management/Views/PolicyOnEmployees/Index.cshtml
@model IEnumerable<Health_Insurance_Management.Models.PolicyOnEmployee>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Admin/Layout/_Layout.cshtml";
}

<section class="content-header">
    <h1>
        Health-Insurance-Management
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Policy</a></li>
        <li class="active">Employee Policy</li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <button class="btn btn-success" style="color: white;">
        @Html.ActionLink("Create New", "Create")
    </button>
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Policies</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="example1" class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>@Html.DisplayNameFor(model => model.Employee.EmployeeName)</th>
                                <th>@Html.DisplayNameFor(model => model.Policy.PolicyName)</th>
                                <th>@Html.DisplayNameFor(model => model.StartDate)</th>
                                <th>@Html.DisplayNameFor(model => model.EndDate)</th>
                                <th>@Html.DisplayNameFor(model => model.Status)</th>
                                <th>@Html.DisplayNameFor(model => model.CreatedDate)</th>
                                <th>@Html.DisplayNameFor(model => model.UpdatedDate)</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Id)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Employee.EmployeeName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Policy.PolicyName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.StartDate)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.EndDate)
                                    </td>
                                    <td>
                                        @if (item.Status == Health_Insurance_Management.Models.Enum.Status.Active)
                                        {
                                            <span class="label label-success">@Html.DisplayFor(modelItem => item.Status)</span>
                                        }
                                        else
                                        {
                                            <span class="label label-warning">@Html.DisplayFor(modelItem => item.Status)</span>
                                        }

                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.CreatedDate)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.UpdatedDate)
                                    </td>
                                    <td>
                                        <div class="btn-group">
                                            <button type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown">Action</button>
                                            <ul class="dropdown-menu" role="menu">
                                                @if (item.Status == Health_Insurance_Management.Models.Enum.Status.Active)
                                                {
                                                    <li><a href="@Url.Action("ChangeStatus", "PolicyOnEmployees", new { id = item.Id })">DeActive</a></li>
                                                }
                                                else
                                                {
                                                    <li><a href="@Url.Action("ChangeStatus", "PolicyOnEmployees", new { id = item.Id })">Active</a></li>
                                                }
                                                <li class="divider"></li>
                                                <li><a href="@Url.Action("Details", "PolicyOnEmployees", new { id = item.Id })">View Detail</a></li>
                                                <li><a href="@Url.Action("Edit", "PolicyOnEmployees", new { id = item.Id })">Edit</a></li>
                                                <li><a href="@Url.Action("Delete", "PolicyOnEmployees", new { id = item.Id })">Delete</a></li>
                                            </ul>
                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>